# Learning and Decision Making

## Laboratory 1: Introduction to scientific computation with Python

In the end of the lab, you should submit all code written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Basic interaction

When you are programming in a Jupyter notebook such as this, you will observe blocks of text preceeded by `In [ ]:` and `Out [ ]:`. These are blocks where you can insert Python code (the "In" blocks), and whose result you can observe as you press "Shift+Enter" (in the "Out" blocks).

For example, try that in the block below.

In [ ]:
s = "Hello, world!"
print(s)

Since you are programming in Python, all your standard primitives are available. You can use conditionals, cycles, inputs and outputs, etc. You also have available all standard Python modules.

In [ ]:
import math

a = 0

# Print a radian --> degree conversion table
while a < 2 * math.pi: 
    print(a, "radians correspond to", a * 90 / math.pi, "degrees.")
    a = a + 0.5

a = input("Please insert a number:\n>> ")

for i in range(5):
    a = math.sqrt(float(a))
    print("Next square root:", a)

if a > 1:
    print(a, "is larger than 1.") 
else: 
    print(a, "is smaller than or equal to 1.")

0 radians correspond to 0.0 degrees.
0.5 radians correspond to 14.32394487827058 degrees.
1.0 radians correspond to 28.64788975654116 degrees.
1.5 radians correspond to 42.97183463481174 degrees.
2.0 radians correspond to 57.29577951308232 degrees.
2.5 radians correspond to 71.6197243913529 degrees.
3.0 radians correspond to 85.94366926962348 degrees.
3.5 radians correspond to 100.26761414789407 degrees.
4.0 radians correspond to 114.59155902616465 degrees.
4.5 radians correspond to 128.91550390443524 degrees.
5.0 radians correspond to 143.2394487827058 degrees.
5.5 radians correspond to 157.5633936609764 degrees.
6.0 radians correspond to 171.88733853924697 degrees.


One important aspect that you should keep in mind is that a notebook such as this one essentially corresponds to a single Python file---and the same scope rules apply as in any other Python file. In particular, if you define a variable in a certain "In" block, that same variable will be accessible in successive blocks. Just make sure that you **run** the "In" blocks in sequence (by pressing Shift+Enter in each block).

In [ ]:
print("The variable s is accessible here:", s)

### 2. Matrices

In your scientific computation you will use three main python libraries: **numpy**, **scipy** and **matplotlib**. The first contains a large collection of numeric types and functions, particularly for matrix manipulation. The second contains a large number of scientific computation utilities (such as optimization sub-modules, etc.). Finally, the third includes plotting functionalities. 

Your work in these labs will involve some level of data manipulation which is done, essentially, in the form of matrix manipulation. In particular, you will use the vast number of matrix manipulation operations offered by **numpy** that, if used proficiently, render computations significantly faster.

Matrices in **numpy** are represented by the type `numpy.array`. The array is initialized as a list of lists, each corresponding to a row of the matrix. There are also several commands to create particular
matrices, such as the identity (`eye`), an all-zeros matrix (`zeros`) or an all-ones matrix (`ones`).

In [ ]:
import numpy as np

A1 = np.array([[1, 2, 3], [4, 5, 6]])
print("2 x 3 array of numbers:")
print(A1)

A2 = np.eye(3)
print("3 x 3 identity:")
print(A2)

A3 = np.zeros((2, 3))
print("2 x 3 array of zeros:")
print(A3)

A4 = np.ones(4);
print("4 x 1 array of ones:")
print(A4)

You can now easily perform standard algebraic operations, such as matrix sum or products. You can also perform indexing, slicing, and other operations, as illustrated in the following examples.

In [ ]:
# = Matrix creation = #

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("3 x 3 matrix:")
print(A)

B = np.arange(1,4)
print("Vector with all numbers between 1 and 3:")
print(B)

C = np.diag(B)
print("Diagonal matrix built from the vector B:")
print(C)

# = Matrix operations = #

# Sum
D = A + np.eye(3)
print("A + I:")
print(D)

# Vector transpose and regular matrix product
E = np.dot(A, B.T)
print("A * B':")
print(E)

# Matrix inverse
F = np.linalg.inv(D)
print("inv(D):")
print(F)

# = Matrix concatenation = #

G = np.append([1, 2, 3], A)
print("Append matrix A to vector [1, 2, 3]:")
print(G)

# When the axis to append is specified, the 
# matrices/vectors must have the correct shape

H1 = np.append(A, [[10, 11, 12]], axis = 0)
H2 = np.append(A, [[4], [7], [10]], axis = 1)
print("Append [10, 11, 12] to A:")
print(H1)

print("Append [[4], [7], [10]] to A:")
print(H2)

# = Matrix indexing = #

# Simple indexing
print("A[0]:", A[0])
print("A[1]:", A[1])
print("A[1, 2]:", A[1, 2])  # More efficient
print("A[0][2]:", A[0][2])  # Less efficient

# -- Slicing

# Rows between 1 and 2 (excluding the latter), 
# columns between 0 and 1 (excluding the latter)
print("A[1:2,0:1]:", A[1:2,0:1])

# All rows except the last two,
# every other column
print("A[:-2,::2]:", A[:-2][::2]) 

I = np.arange(10, 1, -1)
print("Vector with numbers between 10 and 1:")
print(I)

# -- Matrices as indices

# Indexing with a list
print("I[[3, 3, 1, 8]]:", I[np.array([3, 3, 1, 8])])

# Indexing with an nparray
print("I[np.array([3, 3, -3, 8])]:", I[np.array([3, 3, -3, 8])])

# Indexing with an npmatrix
print("I[np.array([[1, 1], [2, 3]])]:", I[np.array([[1, 1], [2, 3]])]) 

Several observations are in order:

* The function `diag` can be used to build a diagonal matrix from a vector or extract a diagonal from a matrix. You can know more about this (and other) functions in numpy in the corresponding documentation or by using the help function. For example, to know more about the `diag` function, you can type `help("numpy.diag")` in the Python prompt, to get something like:

```
>>> help("numpy.diag")
Help on function diag in numpy:

numpy.diag = diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input as a diagonal.
    trace : Sum along diagonals.
    triu : Upper triangle of an array.
    tril : Lower triangle of an array.
    
    Examples
    --------
    >>> x = np.arange(9).reshape((3,3))
    >>> x
    array([[0, 1, 2],
           [3, 4, 5],
           [6, 7, 8]])
    
    >>> np.diag(x)
    array([0, 4, 8])
    >>> np.diag(x, k=1)
    array([1, 5])
    >>> np.diag(x, k=-1)
    array([3, 7])
    
    >>> np.diag(np.diag(x))
    array([[0, 0, 0],
           [0, 4, 0],
           [0, 0, 8]])
```

* You can add, multiply, transpose, invert matrices much as you would in linear algebra
* Indexing and slicing are quite powerful operations. For example, you can use a matrix to index another.

The ability to leverage the powerful indexing and vectorization capabilities of **numpy** is key to producing efficient code. It takes some time to get used to this programming philosophy, but once you do, you will notice a significant improvement in the performance of your code. The impact of good vectorization in the efficiency of your code is illustrated in the following example.

In [ ]:
import numpy.random as rnd
import time

A = rnd.rand(1000,1000)
B = rnd.rand(1000,1000);
C = np.zeros((1000,1000));

t = time.time()

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        C[i, j] = A[i, j] + B[i, j]
    
t1 = time.time() - t

t = time.time()
C = A + B;
t2 = time.time() - t
# 
print("Computation time with cycle (in seconds):", t1)
print("Computation time with numpy operation (in seconds):", t2)

Besides illustrating the importance of optimizing your code to take full advantage of its matrix manipulation capabilities, the previous example introduces several additional elements of the **numpy** syntax, such as:

* The `rand` function from the **numpy.random** module
* The `shape` attribute

---

#### Activity 1.        

Compare the time necessary to compute the cumulative sum of a 10,000 &times; 1 random vector using:

* a for loop;
* a vectorized operation.

For the latter, you may find useful the function `cumsum`.

---

In [ ]:
import numpy.random as rnd
import time

A = rnd.rand(10000,1)
B = A

t = time.time()

res = np.zeros((10000,1))
res[0,0] = A[0,0]

for i in range(A.shape[0]):
    res[i, 0] = res[i-1,0] + A[i,0]

t1 = time.time() - t

t = time.time()
cs = np.cumsum(A)
t2 = time.time() - t

print("Computation time with cycle (in seconds):", t1)
print("Computation time with numpy operation (in seconds):", t2)

---

#### Activity 2.

Compute in 20 &times; 1 vector $y$ where the $n$th entry is given by:

$$ y_n=\prod_{i=1}^n\sum_{j=1}^ij^3 $$

You should use no cycles in your computation.

**Suggestion**: Check the numpy function `cumprod`.

---

In [ ]:
import numpy as np

A = np.arange(1,21)

y = np.cumprod(A**3,dtype="float")

print(y)

### 3. Plotting

The Python module **matplotlib** offers a number of plotting routines that are ideal to display scientific data. The following generates 100 perturbed samples from the function

$$f(x) = 2x$$

and uses these samples to estimate the function $f$.

In [ ]:
%matplotlib notebook
import matplotlib.pyplot as plt

# Create data
x = 100 * rnd.rand(100, 1)
y = 2 * x + 10 * rnd.randn(100, 1)


# Estimate linear relation between X and Y
X = np.append(x, np.ones((100,1)), axis = 1)


f_est = np.dot(np.linalg.pinv(X), y)
y_est = np.dot(X, f_est)

# Plot commands

plt.figure()
plt.plot(x, y_est, hold = True)
plt.plot(x, y, 'x')

plt.xlabel('Input X');
plt.ylabel('Output Y');

plt.title('Linear regression');

Consider more carefully the piece of code above, where we included line numbers for easier reference.

* On lines 5 and 6, the vectors *x* and *y* are created, using mostly functionalities that you already encountered in Sections 1 and 2. The novelty is the function `randn` which is similar to the function `rand` except on their underlying distribution: while `rand` generates random numbers uniformly from the interval [0, 1], `randn` generates normally distributed random numbers with mean 0 and a standard deviation of 1.

* Lines 10-13 estimate a linear relation between *x* and *y* using the data already created. Do not worry about the actual computations, and simply observe the use of matrix concatenation in line 10, and the `pinv` function in line 12. The function `pinv` computes the Moore-Penrose pseudo-inverse of a matrix (see [https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_pseudoinverse])

* Lines 17 through 24 contain the actual plotting commands. In particular:

  * The figure command in line 17 creates a new figure.

  * The plot command in line 18 is responsible for displaying the continuous line in the plot. In here, it is used with its most basic syntax. However, the plot command has a very rich syntax, and you can type `help("mplotlib.pyplot.plot")` to know more about this useful function.
  
  * To avoid subsequent plot commands to erase the existing plot, we turn on the "hold" option to True in the first plot command (line 18).
  
  * The plot command in line 19 plots the original data. Note how the line specification 'x' indicates that, unlike the plot in line 18, this data should not be plotted continuously but instead marking each data-point with an "&times;".
  
* Finally, the commands in lines 21 to 24 are used to include additional information in the plot, such as the labels for both axis and the title for the plot.

---

#### Activity 3.

Recall the definition of $y_n$ in Activity 2:

$$ y_n=\prod_{i=1}^n\sum_{j=1}^ij^3 $$

Plot the value of $y$ against $n$ for $n$ between 1 and 20 (inclusive) using a *linear plot* (obtained
with the command `plot`) and a *logarithmic plot* (using the command `semilogy`). Stack both plots together using the command `subplot`, and comment on the observed differences.

What would you argue to be the usefulness of semi-logarithmic plots?

---

In [ ]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np

n = np.arange(1,21).reshape(20,1)
y = np.cumprod(np.arange(1,21)**3,dtype="float").reshape(20,1)

N = np.append(n, np.ones((20,1)), axis = 1)

f_est = np.dot(np.linalg.pinv(N), y)
y_est = np.dot(N, f_est)

# Plot commands

plt.figure()
plt.plot(n, y, 'o')

plt.plot(n, y, hold = True)
plt.semilogy(x,y)

plt.xlabel('Input n');
plt.ylabel('Output y');

plt.subplot()

plt.title('Linear regression');
plt.show()

[Provide your answer here]

---

#### Activity 4

A hospital is conducting a study on obesity in adult men and, as part of that study, tested the age and body fat for 18 randomly selected adults, with the following results:

| **Age**       |  38  |  27  |  48  |  17  |  33  |  32  |  38  |  38  |  26  |  34  |  33  |  41  |  45  |  46  |  26  |  35  |  22  |  23  | 
| -------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| ** Body fat** | 17.1 | 20.7 | 25.2 | 13.6 | 13.4 | 19.8 | 11.7 | 17.3 | 15.6 | 20.5 | 22.4 | 20.2 | 17.5 | 22.7 |  7.5 | 27.2 |  9.2 | 16.1 |

Write down the data above as two row-vectors `age` and `fat`, and replicate the procedure used to generate the plot above to estimate a linear relation between the two quantities. Plot the relation that you estimated against the real data.

---

In [ ]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np

age = np.array([[38,27,48,17,33,32,38,38,26,34,33,41,45,46,26,35,22,23]]).reshape(18,1)
fat = np.array([[17.1,20.7,25.2,13.6,13.4,19.8,11.7,17.3,15.6,20.5,22.4,20.2,17.5,22.7,7.5,27.2,9.2,16.1]]).reshape(18,1)

# Estimate linear relation between age and fat
X = np.append(age, np.ones((18,1)), axis = 1)

f_est = np.dot(np.linalg.pinv(X), fat)
y_est = np.dot(X, f_est)


# Plot data
plt.figure()
plt.plot(age, y_est, hold = True)
plt.plot(age, fat, 'x')

plt.xlabel('Age');
plt.ylabel('Fat');

plt.title('Age/fat');

